### PR TITLE
Bump the gem version to `0.3.0`

### PR DESCRIPTION
**Pull request by abunashir**
* Minor updates in the readme and `rubocop` config
* Add support for Private Premium client certificate.

### CODE REVIEW

**Comment by abunashir** [comment]
@ronaldtse: This version bump includes the recent changes, could you please do a `rake release` when you have a chance?

**Comment by ronaldtse** [comment]
It's released. Do we want to update `digicert-cli` as well? Thanks!

**Comment by abunashir** [comment]
Thanks, @ronaldtse, I think we kept the certificate type flexible in the CLI so we might need any changes yet, but I will double check and if necessary then I will add the changes there too, Thanks.

**Comment by ronaldtse** [comment]
Thanks @abunashir !

**Comment by abunashir** [comment]
@ronaldtse: Apparently, we do not offer new order creation functionality for the CLI yet, but I still included the latest version to the `CLI` with a version bump, so that RubyGems release should include this as the latest version.

**Comment by ronaldtse** [comment]
So do you want to re-release this?

**Comment by abunashir** [comment]
@ronaldtse: You mean the CLI? No, unless we consider adding order creation interfaces (all type) for the CLI. These are the only interfaces we have so far on the CLI

screenshot 2017-12-11 16 28 43

**Comment by ronaldtse** [comment]
@abunashir it would be wonderful if we can extend order creation in the CLI, if you have the time 😉

**Comment by abunashir** [comment]
Sure thing @ronaldtse, I will put that one the list :)

**Pull request merged**
